[env:unor4wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

; ✅ 串口配置
monitor_speed = 115200
monitor_filters = default


lib_deps = 
    Links2004/WebSockets@^2.4.1
    ArduinoBLE @ 2.0.1
    EEPROM
    bblanchon/ArduinoJson@^7.0.0

; RA4M1 EEPROM 依赖
lib_extra_dirs = 
    ${platformio.packages_dir}/framework-arduinorenesas-uno/libraries/BlockDevices

build_flags = 
    -I ${platformio.packages_dir}/framework-arduinorenesas-uno/libraries/BlockDevices
    -DWEBSOCKETS_DEBUG_LEVEL=0
    -DWEBSOCKETS_NETWORK_IPCLASS=1
    -DWEBSOCKETS_NETWORK_ESPASYNC=1